name: Generate CDN Index

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate index.json from /files
        run: |
          cd files
          find . -type f ! -name 'index.json' | sed 's|^\./||' | jq -R -s -c 'split("\n")[:-1]' > index.json
          cd ..

      - name: Commit and push index.json
        run: |
          git config user.name "cdn-bot"
          git config user.email "cdn-bot@users.noreply.github.com"
          git add files/index.json
          git commit -m "Auto-update files/index.json" || echo "No changes to commit"
          git push
